# This config file for Travis CI utilizes https://github.com/UBC-Snowbots/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:

env:
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ubc-subbots/Jormungandr/$TRAVIS_BRANCH/.rosinstall
    - ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ubc-subbots/Jormungandr/$TRAVIS_BRANCH/.rosinstall
    - TEST_CLANG_FORMAT=TRUE ROS_DISTRO=kinetic UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ubc-subbots/Jormungandr/$TRAVIS_BRANCH/.rosinstall
matrix:
  allow_failures:
      - env: ROS_DISTRO=kinetic ROS_REPO=ros UPSTREAM_WORKSPACE=https://raw.githubusercontent.com/ubc-subbots/Jormungandr/$TRAVIS_BRANCH/.rosinstall

before_script:
    - git clone -q https://github.com/UBC-Snowbots/moveit_ci .moveit_ci
script:
  - source .moveit_ci/travis.sh
